### ISSUE TITLE
Memory Leak Problem.

### ISSUE THREAD

**Issue by bulenttokuzlu** [caronwang/OKEX_V5SDK_GO#3]
In ws_cli.go file in the receive() function

You have a never ending for loop and a defer in it, which causes memory leak.

		ctx := context.Background()
		ctx, cancel := context.WithTimeout(ctx, time.Millisecond*100)
		defer cancel() // THIS IS THE PROBLEM CAUSES MEAMORY LEAK
		select {
		//
		//	Discarding messages can easily lead to data processing errors
		//
		//case <-ctx.Done():
		//	log.Println("Waiting timeout, message discarded - ", data)
		case ch <- &Msg{Timestamp: timestamp, Info: data}:
		}

I do not know how to contribute to your code, just wanted to comment on that.

Thx for the library

**Comment by caronwang** [comment]
Thank you for the comment. I will handle it later.

**Comment by caronwang** [comment]
Code has been committed. Thanks for your advice.

**Comment by bulenttokuzlu** [comment]
Thx.
