### ISSUE TITLE
请问深度校验中以下这段代码是何意

### ISSUE THREAD

**Issue by hpp1106** [caronwang/OKEX_V5SDK_GO#4]
arr := strings.Split(ask[0], ".")
if len(arr) > 1 && len(arr[1]) > 2 {
				fmt.Println("ask数据异常,", checksum, "ask:", ask)
				t.Fatal()
				end <- struct{}{}
				return nil
			} else {
				fmt.Println("bid数据正常,", checksum, "ask:", ask)
			}
一些产品小数点后面有4位，谢谢请指教

**Comment by caronwang** [comment]
这个只是测试的例子，校验某些产品价格深度的精度，价格精度以实际产品为准。
